### PR TITLE
Enforce period and @ rules when validating emails

### PR DESCRIPTION
**Pull request by wojcikstefan**
*For now the PR only contains examples of failing test cases*

### CODE REVIEW

**Comment by thomasst** [comment]
Make sure to also reject emails with multiple periods in the domain name part.

**Comment by thomasst** [comment]
I removed the `test@!example.com` test but added tests to enforce period & @ rules and adjusted the regex. This is obviously still incomplete. We could rely on flanker's addresslib but we won't be perfect here anyways.

**Comment by jkemp101** [comment]
I'm fine switching to flanker for address parsing, I would prefer a standard library we could use across the board for this kind of thing. Do you want to try that now for this PR?

One small nit if we keep the regexes, there is a combination of escaped and unescaped `.` in the `[]`s. I think we could remove a few `\`s.

**Comment by thomasst** [comment]
> I'm fine switching to flanker for address parsing, I would prefer a standard library we could use across the board for this kind of thing. Do you want to try that now for this PR?

Not opposed to it. I'll play around some more with flanker when I get a chance. On the other hand it would be nice to have a basic validation without any dependencies.

> One small nit if we keep the regexes, there is a combination of escaped and unescaped `.` in the `[]`s. I think we could remove a few `\`s.

I think I had some issues with it but I'll take another look if we decide to keep the regexes. I was also wondering if we could simplify `(?:[^\.@\s]|[^\.@\s]\.(?!\.))*`.

**Pull request merged**
